// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/tools/list-tenants.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.90.1";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/helpers.ts
function requireAuth(ctx) {
  if (!ctx.isAuthenticated()) {
    throw new Error("N\xE3o autenticado. Conecte-se com sua conta POSION Tools.");
  }
  return supabaseForUser(ctx);
}
function json(data, structured) {
  return {
    content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
    ...structured ? { structuredContent: structured } : {}
  };
}
function fail(message) {
  return { content: [{ type: "text", text: message }], isError: true };
}
async function resolveTenantId(supabase, tenantSlug) {
  const { data, error } = await supabase.from("tenants").select("id").eq("slug", tenantSlug.trim().toLowerCase()).maybeSingle();
  if (error) throw new Error(error.message);
  if (!data) throw new Error(`Tenant "${tenantSlug}" n\xE3o encontrado ou sem acesso.`);
  return data.id;
}

// src/lib/mcp/tools/list-tenants.ts
var list_tenants_default = defineTool({
  name: "list_tenants",
  title: "Listar clientes (tenants)",
  description: "Lista os tenants/clientes que o usu\xE1rio conectado pode acessar, com slug, nome, plano e status.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    try {
      const supabase = requireAuth(ctx);
      const { data, error } = await supabase.from("tenants").select("id, slug, name, plan, status, segment, business_type").order("name");
      if (error) return fail(error.message);
      return json(data ?? [], { tenants: data ?? [] });
    } catch (e) {
      return fail(e instanceof Error ? e.message : String(e));
    }
  }
});

// src/lib/mcp/tools/list-leads.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z } from "npm:zod@^3.25.76";
var list_leads_default = defineTool2({
  name: "list_leads",
  title: "Listar leads",
  description: "Lista leads de um tenant, com filtro opcional por status/etapa e busca por nome, e-mail ou WhatsApp.",
  inputSchema: {
    tenant_slug: z.string().describe("Slug do tenant, ex: donna-face"),
    status: z.string().optional().describe("Filtrar por status/etapa do lead"),
    search: z.string().optional().describe("Busca por nome, e-mail ou WhatsApp"),
    limit: z.number().int().optional().describe("M\xE1ximo de registros (padr\xE3o 25, m\xE1x 100)")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ tenant_slug, status, search, limit }, ctx) => {
    try {
      const supabase = requireAuth(ctx);
      const tenantId = await resolveTenantId(supabase, tenant_slug);
      const take = Math.min(Math.max(limit ?? 25, 1), 100);
      let query = supabase.from("leads").select(
        "id, nome_completo, whatsapp, email, nome_empresa, status, origem, valor_proposta, created_at"
      ).eq("tenant_id", tenantId).order("created_at", { ascending: false }).limit(take);
      if (status) query = query.eq("status", status);
      if (search) {
        const term = `%${search}%`;
        query = query.or(
          `nome_completo.ilike.${term},email.ilike.${term},whatsapp.ilike.${term},nome_empresa.ilike.${term}`
        );
      }
      const { data, error } = await query;
      if (error) return fail(error.message);
      return json(data ?? [], { leads: data ?? [] });
    } catch (e) {
      return fail(e instanceof Error ? e.message : String(e));
    }
  }
});

// src/lib/mcp/tools/get-lead.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z2 } from "npm:zod@^3.25.76";
var get_lead_default = defineTool3({
  name: "get_lead",
  title: "Detalhar lead",
  description: "Retorna todos os dados de um lead pelo id, incluindo tarefas e agendamentos vinculados.",
  inputSchema: { lead_id: z2.string().describe("UUID do lead") },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ lead_id }, ctx) => {
    try {
      const supabase = requireAuth(ctx);
      const { data: lead, error } = await supabase.from("leads").select("*").eq("id", lead_id).maybeSingle();
      if (error) return fail(error.message);
      if (!lead) return fail("Lead n\xE3o encontrado ou sem acesso.");
      const [{ data: tasks }, { data: appointments }] = await Promise.all([
        supabase.from("lead_tasks").select("id, title, done, due_date, task_type, scheduled_date, scheduled_time").eq("lead_id", lead_id).order("created_at", { ascending: false }).limit(20),
        supabase.from("appointments").select("id, date_time, status, appointment_type, procedure, notes").eq("lead_id", lead_id).order("date_time", { ascending: false }).limit(20)
      ]);
      const payload = { lead, tasks: tasks ?? [], appointments: appointments ?? [] };
      return json(payload, payload);
    } catch (e) {
      return fail(e instanceof Error ? e.message : String(e));
    }
  }
});

// src/lib/mcp/tools/create-lead.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z3 } from "npm:zod@^3.25.76";
var create_lead_default = defineTool4({
  name: "create_lead",
  title: "Criar lead",
  description: "Cria um novo lead no tenant informado.",
  inputSchema: {
    tenant_slug: z3.string().describe("Slug do tenant, ex: donna-face"),
    nome_completo: z3.string().describe("Nome completo do lead"),
    whatsapp: z3.string().optional().describe("WhatsApp com DDD"),
    email: z3.string().optional(),
    nome_empresa: z3.string().optional(),
    origem: z3.string().optional().describe("Origem do lead, ex: indicacao, instagram"),
    status: z3.string().optional().describe("Etapa inicial no funil"),
    observacoes: z3.string().optional()
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    try {
      const supabase = requireAuth(ctx);
      const tenantId = await resolveTenantId(supabase, input.tenant_slug);
      const { tenant_slug: _slug, ...fields } = input;
      const { data, error } = await supabase.from("leads").insert({ ...fields, tenant_id: tenantId }).select("id, nome_completo, whatsapp, status, created_at").maybeSingle();
      if (error) return fail(error.message);
      return json(data, { lead: data });
    } catch (e) {
      return fail(e instanceof Error ? e.message : String(e));
    }
  }
});

// src/lib/mcp/tools/update-lead-status.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z4 } from "npm:zod@^3.25.76";
var update_lead_status_default = defineTool5({
  name: "update_lead_status",
  title: "Mover lead no funil",
  description: "Atualiza o status/etapa de um lead no Kanban. Use list_pipeline_stages para descobrir os status v\xE1lidos.",
  inputSchema: {
    lead_id: z4.string().describe("UUID do lead"),
    status: z4.string().describe("Novo status/stage_key"),
    motivo_perda: z4.string().optional().describe("Motivo da perda, quando mover para perdido")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ lead_id, status, motivo_perda }, ctx) => {
    try {
      const supabase = requireAuth(ctx);
      const { data, error } = await supabase.from("leads").update({ status, ...motivo_perda ? { motivo_perda } : {} }).eq("id", lead_id).select("id, nome_completo, status, motivo_perda").maybeSingle();
      if (error) return fail(error.message);
      if (!data) return fail("Lead n\xE3o encontrado ou sem permiss\xE3o de escrita.");
      return json(data, { lead: data });
    } catch (e) {
      return fail(e instanceof Error ? e.message : String(e));
    }
  }
});

// src/lib/mcp/tools/list-pipeline-stages.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z5 } from "npm:zod@^3.25.76";
var list_pipeline_stages_default = defineTool6({
  name: "list_pipeline_stages",
  title: "Listar etapas do funil",
  description: "Lista as etapas configuradas do Kanban de um tenant (stage_key, t\xEDtulo, ordem).",
  inputSchema: { tenant_slug: z5.string().describe("Slug do tenant") },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ tenant_slug }, ctx) => {
    try {
      const supabase = requireAuth(ctx);
      const tenantId = await resolveTenantId(supabase, tenant_slug);
      const { data, error } = await supabase.from("pipeline_stages").select("stage_key, title, short, hex, position, is_system").eq("tenant_id", tenantId).order("position");
      if (error) return fail(error.message);
      return json(data ?? [], { stages: data ?? [] });
    } catch (e) {
      return fail(e instanceof Error ? e.message : String(e));
    }
  }
});

// src/lib/mcp/tools/list-appointments.ts
import { defineTool as defineTool7 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z6 } from "npm:zod@^3.25.76";
var list_appointments_default = defineTool7({
  name: "list_appointments",
  title: "Listar agendamentos",
  description: "Lista agendamentos de um tenant em um intervalo de datas.",
  inputSchema: {
    tenant_slug: z6.string().describe("Slug do tenant"),
    from: z6.string().optional().describe("Data inicial ISO, ex: 2026-08-01"),
    to: z6.string().optional().describe("Data final ISO, ex: 2026-08-31"),
    status: z6.string().optional().describe("Filtrar por status do agendamento"),
    limit: z6.number().int().optional().describe("M\xE1ximo de registros (padr\xE3o 50, m\xE1x 200)")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ tenant_slug, from, to, status, limit }, ctx) => {
    try {
      const supabase = requireAuth(ctx);
      const tenantId = await resolveTenantId(supabase, tenant_slug);
      const take = Math.min(Math.max(limit ?? 50, 1), 200);
      let query = supabase.from("appointments").select(
        "id, lead_id, client_name, client_phone, date_time, status, appointment_type, procedure, channel"
      ).eq("tenant_id", tenantId).order("date_time", { ascending: true }).limit(take);
      if (from) query = query.gte("date_time", from);
      if (to) query = query.lte("date_time", to);
      if (status) query = query.eq("status", status);
      const { data, error } = await query;
      if (error) return fail(error.message);
      return json(data ?? [], { appointments: data ?? [] });
    } catch (e) {
      return fail(e instanceof Error ? e.message : String(e));
    }
  }
});

// src/lib/mcp/tools/list-tasks.ts
import { defineTool as defineTool8 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z7 } from "npm:zod@^3.25.76";
var list_tasks_default = defineTool8({
  name: "list_tasks",
  title: "Listar tarefas",
  description: "Lista tarefas de leads de um tenant, com filtro de pendentes/conclu\xEDdas.",
  inputSchema: {
    tenant_slug: z7.string().describe("Slug do tenant"),
    done: z7.boolean().optional().describe("true = conclu\xEDdas, false = pendentes"),
    limit: z7.number().int().optional().describe("M\xE1ximo de registros (padr\xE3o 50, m\xE1x 200)")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ tenant_slug, done, limit }, ctx) => {
    try {
      const supabase = requireAuth(ctx);
      const tenantId = await resolveTenantId(supabase, tenant_slug);
      const take = Math.min(Math.max(limit ?? 50, 1), 200);
      let query = supabase.from("lead_tasks").select("id, lead_id, title, done, due_date, task_type, scheduled_date, scheduled_time, phone").eq("tenant_id", tenantId).order("due_date", { ascending: true, nullsFirst: false }).limit(take);
      if (typeof done === "boolean") query = query.eq("done", done);
      const { data, error } = await query;
      if (error) return fail(error.message);
      return json(data ?? [], { tasks: data ?? [] });
    } catch (e) {
      return fail(e instanceof Error ? e.message : String(e));
    }
  }
});

// src/lib/mcp/tools/create-task.ts
import { defineTool as defineTool9 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z8 } from "npm:zod@^3.25.76";
var create_task_default = defineTool9({
  name: "create_task",
  title: "Criar tarefa para um lead",
  description: "Cria uma tarefa vinculada a um lead do tenant informado.",
  inputSchema: {
    tenant_slug: z8.string().describe("Slug do tenant"),
    lead_id: z8.string().describe("UUID do lead"),
    title: z8.string().describe("T\xEDtulo da tarefa"),
    due_date: z8.string().optional().describe("Vencimento em ISO, ex: 2026-08-15T14:00:00Z")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ tenant_slug, lead_id, title, due_date }, ctx) => {
    try {
      const supabase = requireAuth(ctx);
      const tenantId = await resolveTenantId(supabase, tenant_slug);
      const { data, error } = await supabase.from("lead_tasks").insert({
        tenant_id: tenantId,
        lead_id,
        title,
        due_date: due_date ?? null,
        created_by: ctx.getUserId()
      }).select("id, title, done, due_date, lead_id").maybeSingle();
      if (error) return fail(error.message);
      return json(data, { task: data });
    } catch (e) {
      return fail(e instanceof Error ? e.message : String(e));
    }
  }
});

// src/lib/mcp/index.ts
var projectRef = "mbhbflbuawkmtmpjazcj";
var mcp_default = defineMcp({
  name: "posion-growth-leadds",
  title: "posion growth leadds",
  version: "0.1.0",
  instructions: "Ferramentas do CRM POSION Tools. Comece por list_tenants para descobrir o slug do cliente, depois use list_leads, get_lead, list_pipeline_stages, list_appointments e list_tasks para consultar, e create_lead, update_lead_status e create_task para escrever. Todas as opera\xE7\xF5es respeitam as permiss\xF5es do usu\xE1rio conectado.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    list_tenants_default,
    list_leads_default,
    get_lead_default,
    create_lead_default,
    update_lead_status_default,
    list_pipeline_stages_default,
    list_appointments_default,
    list_tasks_default,
    create_task_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
